---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YCIrving.
--- DateTime: 2019-07-13 17:23
---

---@class BagItemModel
local BagItemModel = XT.bindable()

---@type ObjectConfItem
BagItemModel.ObjectConfItem = nil

---@type number
BagItemModel.Count = 0

---@type boolean
BagItemModel.Selected = false

---@type boolean
BagItemModel.TipSpot = false

return BagItemModel