---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YCIrving.
--- DateTime: 2019-07-13 17:23
---
require("common.define")
---@class BagItemCtrl
local BagItemCtrl = XT.class()

function BagItemCtrl.InitData()

end

function BagItemCtrl.CheckCurrentNumUse()
    if(D.BagModel.SelectedItem.NumUse < 1) then
        D.BagModel.SelectedItem.NumUse = 1
    end
    if(D.BagModel.SelectedItem.NumUse > D.BagModel.SelectedItem.CurrentSelectedItem.Count) then
        D.BagModel.SelectedItem.NumUse = D.BagModel.SelectedItem.CurrentSelectedItem.Count
    end
end

-- 更新当前list的Index
function BagItemCtrl.UpdateItemListSelectedIndex()
    if(D.BagModel.SelectedItemList.CurrentSelectedItemList == D.BagModel.ResourcesItemList) then
        D.BagModel.ResourcesSelectedIndex = D.BagModel.SelectedItem.CurrentSelectedIndex
    elseif(D.BagModel.SelectedItemList.CurrentSelectedItemList == D.BagModel.SpeedupItemList) then
        D.BagModel.SpeedupSelectedIndex = D.BagModel.SelectedItem.CurrentSelectedIndex
    elseif(D.BagModel.SelectedItemList.CurrentSelectedItemList == D.BagModel.BoostsItemList) then
        D.BagModel.BoostsSelectedIndex = D.BagModel.SelectedItem.CurrentSelectedIndex
    elseif(D.BagModel.SelectedItemList.CurrentSelectedItemList == D.BagModel.OthersItemList) then
        D.BagModel.OthersSelectedIndex = D.BagModel.SelectedItem.CurrentSelectedIndex
    else
        Log("Current tab error!")
    end
end

function BagItemCtrl.OnSelect(cellIndex, cellModel)

    ---@type BagItemModel
    local m = cellModel

    D.BagModel.SelectedItem.CurrentSelectedItem.Selected = false
    D.BagModel.SelectedItem.CurrentSelectedItem = m
    D.BagModel.SelectedItem.CurrentSelectedItem.Selected = true
    D.BagModel.SelectedItem.CurrentSelectedItem.TipSpot = false;
    D.BagModel.SelectedItem.CurrentSelectedIndex = cellIndex

    if(D.BagModel.SelectedItem.CurrentSelectedItem.ObjectConfItem.UseType == 1) then
        D.BagModel.SelectedItem.NumUse = 1
    end
    BagItemCtrl.UpdateItemListSelectedIndex()
    BagItemCtrl.CheckCurrentNumUse()

    Log("cell index:"..cellIndex.." ,cell model:"..PrintTable(m))
end

return BagItemCtrl
