---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by YCIrving.
--- DateTime: 2019-07-11 18:12
---

--[[---@class ItemLists
local ItemLists = XT.bindable()
---@type BagItemModel[]
ItemLists.ResourcesItemList = {}
---@type BagItemModel[]
ItemLists.SpeedupItemList = {}
---@type BagItemModel[]
ItemLists.BoostsItemList = {}
---@type BagItemModel[]
ItemLists.OthersItemList = {}]]

--[[---@class CurrentSelection
local CurrentSelection = XT.bindable()
---@type number
CurrentSelection.CurrentSelectedItemListIndex = 1
---@type number
CurrentSelection.ResourcesSelectedIndex = 0
---@type number
CurrentSelection.SpeedupSelectedIndex = 0
---@type number
CurrentSelection.BoostsSelectedIndex = 0
---@type number
CurrentSelection.OthersSelectedIndex = 0]]


---@class SelectedItem
local SelectedItem = XT.bindable()
---@type BagItemModel
SelectedItem.CurrentSelectedItem = nil
---@type number
SelectedItem.CurrentSelectedIndex = 0
---@type number
SelectedItem.NumUse = 1
---@type boolean
SelectedItem.UseUp = false


---@class SelectedItemList
local SelectedItemList = XT.bindable()
---@type BagItemModel[]
SelectedItemList.CurrentSelectedItemList = {}
---@type boolean
SelectedItemList.CurrentSelectedItemListEmpty = false

---@class BagModel
local BagModel = XT.bindable()

---@type
BagModel.SelectedItem = SelectedItem()
---@type
BagModel.SelectedItemList = SelectedItemList()
---@type number
BagModel.ResourcesSelectedIndex = 0
---@type number
BagModel.SpeedupSelectedIndex = 0
---@type number
BagModel.BoostsSelectedIndex = 0
---@type number
BagModel.OthersSelectedIndex = 0
---@type BagItemModel[]
BagModel.ResourcesItemList = {}
---@type BagItemModel[]
BagModel.SpeedupItemList = {}
---@type BagItemModel[]
BagModel.BoostsItemList = {}
---@type BagItemModel[]
BagModel.OthersItemList = {}
---@type boolean
BagModel.FirstInit = true
---@type ChestItemModel[]
BagModel.AddedItemList = {}

return BagModel
