---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ycirving.
--- DateTime: 2019-08-09 19:34
---

---@class ChestModel
local ChestModel = XT.bindable()

---@tyoe ChestItemModel
ChestModel.CurrentSelectedChestItem = nil
---@type TMPro.TMP_Text
ChestModel.Claim = nil
---@type function
ChestModel.OnClaim = nil

---@type CS.ModelShark.TooltipTrigger
ChestModel.Trigger = nil

---@type CS.Wod.UI.Ext.Empty4Raycast
ChestModel.RayCast = nil

return ChestModel