---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ycirving.
--- DateTime: 2019-08-13 17:42
---

---@class ChestItemTipsModel
local ChestItemTipsModel = XT.bindable()

---@type boolean
ChestItemTipsModel.Active = false

return ChestItemTipsModel