---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ycirving.
--- DateTime: 2019-08-13 12:11
---
require "common/define"

---@class ChestItemView
local ChestItemView = XT.class()

--start
---@type UnityEngine.UI.Image
ChestItemView._objectIcon = nil
---@type UnityEngine.UI.Image
ChestItemView._bgIcon = nil
---@type UnityEngine.UI.Image
ChestItemView._cvSelected = nil
---@type UnityEngine.UI.Image
ChestItemView._tipSpot = nil
---@type UnityEngine.UI.Button
ChestItemView._btnSelect = nil
---@type TMPro.TMP_Text
ChestItemView._lbNum = nil
--end

--------------------- base function begin ------------------------------------------------------------------------------
function ChestItemView:Awake()

end

function ChestItemView:Start()
    self:Init()
    self:AddListener()
end

function ChestItemView:Init()

end

function ChestItemView:Update()

end

function ChestItemView:OnDestroy()
    self:OnClose()
end

function ChestItemView:AddListener()
    self._btnSelect.onClick:AddListener(function () CT.ChestItemCtrl.OnSelectChestItem(self.CellIndex, self.CellModel) end)
end

function ChestItemView:RemoveListener()
    self._btnSelect.onClick:RemoveListener(function () CT.ChestItemCtrl.OnSelectChestItem(self.CellIndex, self.CellModel) end )
end

function ChestItemView:OnClose()
    self:OnClean()
    self:RemoveListener()
    self:UnBind()
end

function ChestItemView:OnClean()

end

function ChestItemView.Bind(model, view)

    XT.bind(view, model, function (m)
        ---@type ChestItemView
        local v = view
        ---@type ChestItemModel
        local m = model


        -- 修改图标和背景
        UGUIUtil.SetImage(v._objectIcon, m.ObjectConfItem.Atlas, m.ObjectConfItem.Icon)
        -- UGUIUtil.SetImage(v._bgIcon, "icon", m.ObjectConfItem.Icon)

        --[[        v._objectIcon:SetSprite("icon", m.ObjectConfItem.Icon)
                v._bgIcon:SetSprite("Chest","bg_itemback_blue")]]

        -- 显示选中边框
        v._cvSelected.gameObject:SetActive(m.Selected)
        -- 显示右下数量
        if(m.Count > 9999) then
            v._lbNum.text = "9999+"
        else
            v._lbNum.text = m.Count
        end


        -- 显示小红点
        v._tipSpot.gameObject:SetActive(m.TipSpot)

    end)
end

function ChestItemView:UnBind()
    Log("ChestItemView:UnBind" .. tostring(self))
    XT.unbind(self)
end

--------------------- base function end ------------------------------------------------------------------------------
return ChestItemView