---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ycirving.
--- DateTime: 2019-08-13 17:42
---

require("common.define")
local MsgKey = require("model.MsgKey")

---@class ChestItemTipsView
local ChestItemTipsView = XT.class()

--start
---@type TMPro.TMP_Text
ChestItemTipsView._lbChestItemName = nil
---@type TMPro.TMP_Text
ChestItemTipsView._lbChestItemDec = nil
--end

--------------------- base function begin --------------------------------------------------------------------------------
function ChestItemTipsView:Awake()

end

function ChestItemTipsView:Start()
    self:Init()
    self:AddListener()
end

function ChestItemTipsView:Init()
    if D.ChestItemTipsModel == nil then
        local model = MT.ChestItemTipsModel()
        self.Model = model
        D.ChestItemTipsModel = model
        self:Bind(self, model)
    else
        self:Bind(self, D.ChestItemTipsModel)
    end

    CT.ChestItemTipsCtrl.InitData()
end

function ChestItemTipsView:Update()

end

function ChestItemTipsView:OnDestroy()
    self:OnClose()
end

function ChestItemTipsView:AddListener()

end

function ChestItemTipsView:RemoveListener()

end

function ChestItemTipsView:OnClose()
    self:RemoveListener()
    self:UnBind()
    self:OnClean()
    Log("ChestItemTipsView:OnClose")
end

function ChestItemTipsView:OnClean()

end

function ChestItemTipsView:UnBind()
    XT.unbind(self)
    Log("ChestItemTipsView UnBind")
end



function ChestItemTipsView:Bind(view, model)
    XT.bind(view, model,function (m)
        ---@type ChestItemTipsView
        local v = view
        ---@type ChestItemTipsModel
        local m = model

        local currentSelectedChestItem = D.ChestModel.CurrentSelectedChestItem
        if currentSelectedChestItem ==  nil then return end
        Log("currentSelectedChestItem:"..tostring(currentSelectedChestItem.ObjectConfItem.Name))
        v._lbChestItemName.text = currentSelectedChestItem.ObjectConfItem.Name
        v._lbChestItemDec.text = currentSelectedChestItem.ObjectConfItem.Dec

        --local mm = D.HeroDetailModel.SkillList[index].HeroItemConf
        --if index >= 1 and index <= 2 then --主动技能
        --    v._lbSkillName.text =  MsgKey.get(1310,  D.HeroDetailModel.SkillList[index].SkillLevel).." "..mm.Skill[index].Name
        --    v._lbSkillContent.text = mm.Skill[index].Des
        --    v._lbSkillType.text = MsgKey.get(1312)
        --    v._lbSkillValue.text = D.HeroDetailModel.SkillList[index].SkillATKValue
        --elseif index >= 3 and index <= 6 then
        --    v._lbSkillName.text = MsgKey.get(1310,  D.HeroDetailModel.SkillList[index].SkillLevel).." "..mm.SkillPassive[index - 2].Name
        --    v._lbSkillContent.text = mm.SkillPassive[index - 2].Des
        --    v._lbSkillType.text = MsgKey.get(1313)
        --    v._lbSkillValue.text = D.HeroDetailModel.SkillList[index - 2].SkillATKValue
        --end

        Log("ChestItemTipsView bind XT.bind")
    end)
    Log("ChestItemTipsView bind")
end
--------------------- base function end --------------------------------------------------------------------------------

return ChestItemTipsView