---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ycirving.
--- DateTime: 2019-08-09 19:34
---

require("common.define")
local MsgKey = require("model.MsgKey")

---@class ChestView
local ChestView = XT.class()

--start
---@type Wod.UI.BasicGridAdapter
ChestView._addedItemListGridView = nil
---@type UnityEngine.UI.Button
ChestView._btnClaim = nil
---@type TMPro.TMP_Text
ChestView._lbClaim = nil
---@type ModelShark.TooltipTrigger
ChestView._triggerTips = nil
--end



--------------------- base function begin --------------------------------------------------------------------------------
function ChestView:Awake()

end

function ChestView:Start()
    self:Init()
    self:AddListener()
end

function ChestView:Init()
    if D.ChestModel == nil then
        local model = MT.ChestModel()
        self.Model = model
        D.ChestModel = model
        self:Bind(self, model)
    else
        self:Bind(self, D.ChestModel)
        self.Model = D.ChestModel
    end

    self._addedItemListGridView.OnStart = function()
        self:BindAddedItemList()
    end

    self._triggerTips.OnStart = function()
        self:InitChestItemTips()
    end


    CT.ChestCtrl.InitData()
end

function ChestView:Update()

end

function ChestView:OnDestroy()
    self:OnClose()
end

function ChestView:AddListener()
    self._btnClaim.onClick:AddListener(CT.ChestCtrl.OnBtnClaim)
    Event.AddListener(UIEventType.SHOW_UI_OPEN_CHEST_PANEL, self.OnShowChest, self, "ChestView")
end

function ChestView:RemoveListener()
    self._btnClaim.onClick:RemoveListener(CT.ChestCtrl.OnBtnClaim)
    Event.RemoveListener(UIEventType.SHOW_UI_OPEN_CHEST_PANEL, self.OnShowChest, self, "ChestView")
end

function ChestView:OnClose()
    self:RemoveListener()
    self:UnBind()
    self:OnClean()
end

function ChestView:OnClean()
    CS.Wod.UI.ModelShark.TooltipManager.Instance:ResetToolTipsParent()
end

function ChestView:UnBind()
    XT.unbind(self)
    Log("ChestView UnBind")
end

function ChestView:BindAddedItemList()
    Log("ChestView:BindAddedItemList()")
    XT.BindGrid(self, self._addedItemListGridView, D.BagModel.AddedItemList, VT.ChestItemView.Bind)

    --XT.bind(self, D.ChestModel.AddedItemList, function (m, v)
    --    Log("Bind Added Item List")
    --    XT.BindGrid(self, self._addedItemListGridView, D.ChestModel.AddedItemList, VT.ChestView.Bind)
    --end)
end


function ChestView:Bind(view, model)

    XT.bind(view, model,function (m)
        ---@type ChestView
        local v = view
        ---@type ChestModel
        local m = model
        v._lbClaim.text = m.Claim
        --Log("MessageBoxView bind XT.bind")
    end)
    --Log("MessageBoxView bind")
end
--------------------- base function end --------------------------------------------------------------------------------

function ChestView:OnShowChest(data)
    --if data.AddedItemList == nil then
    --    D.ChestModel.AddedItemList = nil
    --else
    --    D.ChestModel.AddedItemList = data.AddedItemList
    --end
    if data.Claim == nil then
        D.ChestModel.Claim = "Claim"
    else
        D.ChestModel.Claim = data.Claim
    end

    if data.OnClaim ~= nil then
        D.ChestModel.OnClaim = data.OnClaim
    else
        --self._btnClaim.gameObject:SetActive(false)
        D.ChestModel.OnClaim = nil
    end
end

function ChestView:InitChestItemTips()
    D.ChestModel.Trigger = self._triggerTips:GetComponent("TooltipTrigger")

    --local goContainer = CS.ModelShark.TooltipManager.Instance.TooltipContainer

    --if goContainer then
    --    local Pointer = UGUIUtil.GetOrCreate(goContainer,typeof(CS.Wod.UI.Ext.PointerUpDownListener))
    --    D.ChestModel.RayCast = UGUIUtil.GetOrCreate(goContainer,typeof(CS.Wod.UI.Ext.Empty4Raycast))
    --    D.ChestModel.RayCast.enabled = false
    --    Pointer.ondown = function(evt)
    --        CT.ChestCtrl.OnTipsPointerDown(evt)
    --    end
    --
    --    Pointer.onup = function(evt)
    --        CT.ChestCtrl.OnTipsPointerUp(evt)
    --    end
    --end


    local goContainer = CS.Wod.UI.ModelShark.TooltipManager.Instance.TooltipContainer

    if goContainer then
        local Pointer = UGUIUtil.GetOrCreate(goContainer,typeof(CS.Wod.UI.Ext.TipsPointerUpDownListener))
        D.ChestModel.RayCast = UGUIUtil.GetOrCreate(goContainer,typeof(CS.Wod.UI.Ext.Empty4Raycast))
        Pointer.onup = function(evt)
            D.ChestModel.RayCast.enabled = false
        end
    end
end


return ChestView