---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ycirving.
--- DateTime: 2019-08-13 12:10
---

require("common.define")

---@class ChestItemCtrl
local ChestItemCtrl = XT.class()

function ChestItemCtrl.InitData()

end

function ChestItemCtrl.OnSelectChestItem(cellIndex, cellModel)
    ---@type ChestItemModel
    local m = cellModel
    Log("cell index:"..cellIndex.." ,cell model:"..PrintTable(m))

    if(D.ChestModel.CurrentSelectedChestItem ~= nil) then
        D.ChestModel.CurrentSelectedChestItem.Selected = false;
    end
    D.ChestModel.CurrentSelectedChestItem = m
    D.ChestModel.CurrentSelectedChestItem.Selected = true;
    --D.HeroDetailModel.SelectSkill = cellIndex

    if D.ChestItemTipsModel ~= nil then
        D.ChestItemTipsModel.Active = true
    end
    --ChestItemCtrl.ShowTips()
    XT.UIManager:ShowTips(D.ChestModel.Trigger, D.ChestModel.RayCast)
end

--function ChestItemCtrl.ShowTips()
--    Log("ChestItemCtrl.ShowTips()")
--    CS.ModelShark.TooltipManager.Instance:HideAll()
--    D.ChestModel.Trigger:Popup(2, nil)
--    D.ChestModel.RayCast.enabled = true
--end

return  ChestItemCtrl