---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ycirving.
--- DateTime: 2019-08-13 12:11
---

---@class ChestItemModel
local ChestItemModel = XT.bindable()

---@type ObjectConfItem
ChestItemModel.ObjectConfItem = nil

---@type number
ChestItemModel.Count = 0

---@type boolean
ChestItemModel.Selected = false

---@type boolean
ChestItemModel.TipSpot = false

return ChestItemModel