---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ycirving.
--- DateTime: 2019-08-13 17:41
---

---@class ChestItemTipsCtrl
local ChestItemTipsCtrl = XT.class()


function ChestItemTipsCtrl.InitData()
    Log(" ChestItemTipsCtrl.InitData")
end

return ChestItemTipsCtrl