---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ycirving.
--- DateTime: 2019-08-09 19:35
---

---@class ChestCtrl
local ChestCtrl = XT.class()
local BindableList = XT.bindable()

function ChestCtrl.InitData()
    D.ChestModel.AddedItemList = BindableList()
end

function ChestCtrl.OnBtnClaim()
    ChestCtrl.OnClose()
    if D.ChestModel.OnClaim ~= nil then
        D.ChestModel.OnClaim()
    end
end

function ChestCtrl.OnClose()
    XT.UIManager.Instance:OnDestroy("UIOpenChest")
end

--function ChestCtrl.OnTipsPointerDown(evt)
--    Log("OnTipsPointerDown")
--    CS.ModelShark.TooltipManager.Instance:HideAll()
--end
--
--function ChestCtrl.OnTipsPointerUp(evt)
--    Log("OnTipsPointerUp")
--    D.ChestModel.RayCast.enabled = false
--end

return ChestCtrl
